/* Problem 1: Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

int fiboSpecial()
{
    int runningTotal = 0;
    int a = 0, b = 1, temp = 0;
    while( a < 4000000 ) {
        temp = b;
        b += a;
        a = temp;
        if( a%2 == 0 )
            runningTotal += a;
    }	
    return runningTotal;
}


int main()
{
    int runningTotal = 0;
    runningTotal = fiboSpecial(); 
    std::cout << "The sum is: " << runningTotal << "." << std::endl;
    std::cin.get();
    return 0;
}

